### ISSUE TITLE
Unresolved elements  when packin JPIERE-0469-03.zip idempiere 7.1

### ISSUE THREAD

**Issue by djoudi** [JPiere/jpiere.plugin.groupware#1]
Unresolved elements  when packin JPIERE-0469-03.zip idempiere 7.1

![image](https://user-images.githubusercontent.com/152725/109053610-2ecd7980-76dd-11eb-8a9e-593ad0766732.png)

**Comment by djoudi** [comment]
@JPiere

**Comment by JPiere** [comment]
Please try JPiere8.2 or JPiere7.1-final  install package.
https://ja.osdn.net/projects/jpiere/releases/

**Comment by JPiere** [comment]
Update 2pack JPIERE-0469-03.zip - 2021-07-16
