### ISSUE TITLE
Idempiere 8.2

### ISSUE THREAD

**Issue by chibsta** [JPiere/jpiere.plugin.groupware#2]
Hi,

I am eager to use your plugin on Idempiere 8.2 on an Ubuntu 18 server. I've tried to install the pack ins and the plugin on my server but I cannot get the ToDo Calendar menu. Kindly assist.

Regards,

**Comment by JPiere** [comment]
I don't know what wrong from your report.

**Comment by JPiere** [comment]
Did you kick Role Access Update process? 
Did you confirm access control of Role?

**Comment by JPiere** [comment]
I think this issue is not problem of this plugin.
SO, I closed this issue.
